# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js 

on:
  push:
    branches:
      - '*'

jobs:
  my-job:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x]
    env:
      ATLAS_USERNAME: ${{ secrets.ATLAS_USERNAME }}
      ATLAS_PASSWORD: ${{ secrets.ATLAS_PASSWORD }}

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Install dependencies in backend directory
      run: |
        cd backend
        npm run clean
        npm install

    - name: Run tests in backend directory
      run: |
        cd backend
        npm run test

    - name: Install dependencies in frontend directory
      run: |
        cd frontend
        npm run clean
        npm install --legacy-peer-deps
        npm update --save-dev jest jest-environment-jsdom --force

    - name: Lint backend routes
      run: |
        cd backend
        npm run eslint -- routes/**/*.js

    - name: Run tests in frontend directory
      run: |
        cd frontend
        npm run test
